trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
 
steps:
- script: |
    terraform --version 
    sudo apt update
    
    # Clone your GitHub repository
    git clone https://github.com/rainrajon/new_one.git
 
    # Change directory to your repository
    # cd your-repo
 
    # Run the Python script
    az account set --subscription 992de8fd-65e6-4178-8d06-5f7955ad4425
    az login --service-principal -u 4de44e41-0451-470a-9643-c04a3978db13 -p _yN8Q~foCfmhjjwOVWOiDEkRyuLAWvoGQT1JDbgJ --tenant aad3cd3b-f269-4d1d-abea-18ea92f2ce38

    terraform init
    terraform plan -out main.tfplan
    terraform apply main.tfplan
  displayName: 'Terraform code'